name: TigerVNC with LocalXpose
on: [workflow_dispatch]

jobs:
  vnc:
    runs-on: ubuntu-latest
    steps:
    - name: Install VNC and XFCE
      run: |
        sudo apt-get update
        sudo apt-get install -y tigervnc-standalone-server xfce4 wget
        
    - name: Set VNC password
      run: |
        mkdir -p ~/.vnc
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        
    - name: Download LocalXpose
      run: |
        wget -q https://lxpse.com/linux/loclx -O loclx
        chmod +x loclx
        
    - name: Start VNC and LocalXpose tunnel
      run: |
        # Start VNC server
        vncserver -localhost :1
        export DISPLAY=:1
        xfce4-session &
        
        # Start LocalXpose with YOUR token
        echo "🚀 Starting LocalXpose tunnel..."
        ./loclx tunnel tcp --port 5901 --token AuyMjNb72nWAmt7MfWII0tOSwo1NsbEK716DUzVa
