name: Localtonet API + VNC Test
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install VNC
      run: |
        sudo apt-get update
        sudo apt-get install -y tigervnc-standalone-server xfce4
        
    - name: Start VNC
      run: |
        mkdir -p ~/.vnc
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        vncserver -localhost :1
        export DISPLAY=:1
        xfce4-session &
        echo "✅ VNC started on :1"
        
    - name: Create Localtonet tunnel via API
      run: |
        response=$(curl -s -X POST "https://api.localtonet.com/tunnel" \
          -H "Authorization: Bearer Aw7xeMfRbuOBHpkoEgT3z8KYn6P0Sqhv1" \
          -H "Content-Type: application/json" \
          -d '{"type": "tcp", "local_port": 5901}')
        echo "API Response: $response"
