name: TigerVNC with LocalXpose
onname: TigerVNC with Localtonet
on: [workflow_dispatch]

jobs:
  vnc:
    runs-on: ubuntu-latest
    steps:
    - name: Install VNC and XFCE
      run: |
        sudo apt-get update
        sudo apt-get install -y tigervnc-standalone-server xfce4 wget
        
    - name: Set VNC password
      run: |
        mkdir -p ~/.vnc
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        
    - name: Download Localtonet
      run: |
        wget -q https://localtonet.com/download/linux -O localtonet
        chmod +x localtonet
        
    - name: Start VNC and Localtonet
      run: |
        vncserver -localhost :1
        export DISPLAY=:1
        xfce4-session &
        ./localtonet tcp --port 5901 --token Aw7xeMfRbuOBHpkoEgT3z8KYn6P0Sqhv1
