
name: TigerVNC with Serveo
on: [workflow_dispatch]

jobs:
  vnc:
    runs-on: ubuntu-latest
    steps:
    - name: Install VNC and XFCE
      run: |
        sudo apt-get update
        sudo apt-get install -y tigervnc-standalone-server xfce4
        
    - name: Set VNC password
      run: |
        mkdir -p ~/.vnc
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        
    - name: Start VNC and Serveo tunnel
      run: |
        # Start VNC server
        vncserver -localhost :1
        export DISPLAY=:1
        xfce4-session &
        
        # Start Serveo tunnel (this will show the public URL)
        echo "🚀 Starting Serveo tunnel..."
        ssh -o StrictHostKeyChecking=no -R 0:localhost:5901 serveo.net
