
name: TigerVNC Server
on: [workflow_dispatch]

jobs:
  tigervnc:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y tigervnc-standalone-server xfce4 wget
        
    - name: Setup ngrok
      run: |
        wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar xzf ngrok-v3-stable-linux-amd64.tgz
        ./ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Set VNC password
      run: |
        mkdir -p ~/.vnc
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        
    - name: Start VNC and tunnel
      run: |
        # Start VNC
        vncserver -localhost :1
        export DISPLAY=:1
        xfce4-session &
        
        # Start ngrok tunnel
        ./ngrok tcp 5901 --log=stdout > ngrok.log &
        
        # Get public URL
        sleep 10
        echo "🔗 Public VNC URL:"
        curl -s http://localhost:4040/api/tunnels | grep -o 'public_url":"[^"]*' | cut -d'"' -f3
        
        # Keep running
        sleep 3000
